//
//  File.swift
//  
//
//  Created by Yuki Kuwashima on 2023/10/06.
//

import Foundation

public enum CSSColor: String {
    case aliceblue
    case antiquewhite
    case aqua
    case aquamarine
    case azure
    case beige
    case bisque
    case black
    case blanchedalmond
    case blue
    case blueviolet
    case brown
    case burlywood
    case cadetblue
    case chartreuse
    case chocolate
    case coral
    case cornflowerblue
    case cornsilk
    case crimson
    case cyan
    case darkblue
    case darkcyan
    case darkgoldenrod
    case darkgray
    case darkgreen
    case darkgrey
    case darkkhaki
    case darkmagenta
    case darkolivegreen
    case darkorange
    case darkorchid
    case darkred
    case darksalmon
    case darkseagreen
    case darkslateblue
    case darkslategray
    case darkslategrey
    case darkturquoise
    case darkviolet
    case deeppink
    case deepskyblue
    case dimgray
    case dimgrey
    case dodgerblue
    case firebrick
    case floralwhite
    case forestgreen
    case fuchsia
    case gainsboro
    case ghostwhite
    case gold
    case goldenrod
    case gray
    case green
    case greenyellow
    case grey
    case honeydew
    case hotpink
    case indianred
    case indigo
    case ivory
    case khaki
    case lavender
    case lavenderblush
    case lawngreen
    case lemonchiffon
    case lightblue
    case lightcoral
    case lightcyan
    case lightgoldenrodyellow
    case lightgray
    case lightgreen
    case lightgrey
    case lightpink
    case lightsalmon
    case lightseagreen
    case lightskyblue
    case lightslategray
    case lightslategrey
    case lightsteelblue
    case lightyellow
    case lime
    case limegreen
    case linen
    case magenta
    case maroon
    case mediumaquamarine
    case mediumblue
    case mediumorchid
    case mediumpurple
    case mediumseagreen
    case mediumslateblue
    case mediumspringgreen
    case mediumturquoise
    case mediumvioletred
    case midnightblue
    case mintcream
    case mistyrose
    case moccasin
    case navajowhite
    case navy
    case oldlace
    case olive
    case olivedrab
    case orange
    case orangered
    case orchid
    case palegoldenrod
    case palegreen
    case paleturquoise
    case palevioletred
    case papayawhip
    case peachpuff
    case peru
    case pink
    case plum
    case powderblue
    case purple
    case rebeccapurple
    case red
    case rosybrown
    case royalblue
    case saddlebrown
    case salmon
    case sandybrown
    case seagreen
    case seashell
    case sienna
    case silver
    case skyblue
    case slateblue
    case slategray
    case slategrey
    case snow
    case springgreen
    case steelblue
    case tan
    case teal
    case thistle
    case tomato
    case turquoise
    case violet
    case wheat
    case white
    case whitesmoke
    case yellow
    case yellowgreen
}
